# Generated by Django 5.0 on 2026-07-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymove', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField(help_text='Experience in years')),
                ('join_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
