# Generated by Django 5.0 on 2026-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymove', '0003_member_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
