# Generated by Django 5.0 on 2026-07-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymove', '0004_membershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='gymove.membershipplan'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
