# Generated by Django 5.0 on 2026-07-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymove', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lock_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
