# Generated by Django 5.0 on 2026-07-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymove', '0007_userprofile_lock_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='tempuser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
